### ISSUE TITLE
Updating Issue with existing relationships in postgres

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#131]
When updating I get the below, this looks to prevent further updates from happening also. Any way around this?

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: constraint "releases_sfv_id_fkey" for relation "releases" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 9, in <module>
    load_entry_point('alembic==0.7.2', 'console_scripts', 'alembic')()
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 399, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 393, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.4/dist-packages/alembic/config.py", line 376, in run_cmd
    **dict((k, getattr(options, k)) for k in kwarg)
  File "/usr/local/lib/python3.4/dist-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.4/dist-packages/alembic/script.py", line 382, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python3.4/dist-packages/alembic/util.py", line 241, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.4/dist-packages/alembic/compat.py", line 68, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap>", line 539, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1614, in load_module
  File "<frozen importlib._bootstrap>", line 596, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "alembic/env.py", line 71, in <module>
    run_migrations_online()
  File "alembic/env.py", line 64, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/usr/local/lib/python3.4/dist-packages/alembic/environment.py", line 742, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.4/dist-packages/alembic/migration.py", line 305, in run_migrations
    step.migration_fn(**kw)
  File "/opt/pynab/alembic/versions/c5c72142b8_add_missing_cascades_to_binaries.py", line 26, in upgrade
    op.create_foreign_key('releases_sfv_id_fkey', 'releases', 'sfvs', ['sfv_id'], ['id'], ondelete='CASCADE')
  File "<string>", line 7, in create_foreign_key
  File "/usr/local/lib/python3.4/dist-packages/alembic/operations.py", line 748, in create_foreign_key
    **dialect_kw)
  File "/usr/local/lib/python3.4/dist-packages/alembic/ddl/impl.py", line 168, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/usr/local/lib/python3.4/dist-packages/alembic/ddl/impl.py", line 106, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/ddl.py", line 69, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 783, in _execute_ddl
    compiled
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) constraint "releases_sfv_id_fkey" for relation "releases" already exists
 'ALTER TABLE releases ADD CONSTRAINT releases_sfv_id_fkey FOREIGN KEY(sfv_id) REFERENCES sfvs (id) ON DELETE CASCADE' {}

**Comment by brookesy2** [comment]
I just dropped the column as it only had nulls in it anyway. After that all was fine.
