### ISSUE TITLE
Backfill error

### ISSUE THREAD

**Issue by AlanKK** [Murodese/pynab#132]
This happened after backfill ran for a few hours.  It has happened twice.

user@my-pc:/var/www/pynab$ python3 scripts/backfill.py 
Starting backfill. Ensure that dead_binary_age is set to 0 in config.py!

Traceback (most recent call last):
  File "/var/www/pynab/scripts/../pynab/server.py", line 101, in scan
    self.connection.group(group_name)
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 785, in group
    resp = self._shortcmd('GROUP ' + name)
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 626, in _shortcmd
    return self._getresp()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 475, in _getresp
    resp = self._getline()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 463, in _getline
    if not line: raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/scripts/../pynab/groups.py", line 78, in scan
    status, parts, messages, missed = server.scan(group_name, first=begin, last=end)
  File "/var/www/pynab/scripts/../pynab/server.py", line 119, in scan
    self.connection.quit()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 1080, in quit
    resp = self._shortcmd('QUIT')
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 626, in _shortcmd
    return self._getresp()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 475, in _getresp
    resp = self._getline()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 463, in _getline
    if not line: raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 1080, in quit
    resp = self._shortcmd('QUIT')
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 625, in _shortcmd
    self._putcmd(line)
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 452, in _putcmd
    self._putline(line)
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 444, in _putline
    self.file.write(line)
AttributeError: 'NNTP_SSL' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/backfill.py", line 41, in <module>
    if pynab.groups.scan(group.name, direction='backward'):
  File "/var/www/pynab/scripts/../pynab/groups.py", line 116, in scan
    return True
  File "/var/www/pynab/scripts/../pynab/server.py", line 31, in __exit__
    self.connection.quit()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 1082, in quit
    self._close()
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 1234, in _close
    _NNTPBase._close(self)
  File "/var/www/pynab/scripts/../lib/nntplib.py", line 1073, in _close
    self.file.close()
AttributeError: 'NNTP_SSL' object has no attribute 'file'

**Comment by Murodese** [comment]
I think I know what this is. Use scan.py instead, ie.

`python3 scan.py --backfill` # backfills all active groups to default in config
`python3 scan.py --backfill --group <group> --date <date>` # for a specific group to a specific date

You'll probably get another error: `scan: nntp server is flipping out, hopefully they fix their shit`. If that's happening with a single group, ignore it - it's a news server problem and it'll come good later. If it's happening with every group, possibly your news provider is dying (try swapping to european servers or US vice versa).

I'll remove that old backfill script.

**Comment by AlanKK** [comment]
OK.  I think my provider my disconnect me after a few hours.

**Comment by Murodese** [comment]
Varies a bit. I'm with supernews and I've had particular groups (a.b.hdtv) go down for a period of days at a time, only to come back up later.

**Comment by AlanKK** [comment]
It looks like "python3 pynab.py backfill" is valid as well.

**Comment by Murodese** [comment]
Yep, that works as well but you can't pass it group/date arguments. It'll just backfill active groups to the default. If you want to do a specific group or to a specific date, you need to use `scan.py`.

**Comment by AlanKK** [comment]
Just got it and it recovered.  Nice.

2015-01-18 09:48:04 ERROR server: [alt.binaries.games]: nntp error
2015-01-18 09:48:04 ERROR server: suspected dead nntp connection, restarting
2015-01-18 09:48:04 ERROR scan: nntp server is flipping out, hopefully they fix their shit

**Comment by Murodese** [comment]
Yep, cool. If it's a one off error it's not a problem - pynab will recover. If it's a news server problem, it'll just skip that group until it starts working again.
