### ISSUE TITLE
Interesting exceptions during scan update

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#170]
I think these started after updating to 1.5.1.
Didn't notice these until looking at the log files (daemon is configured to restart automatically on crash):
```
Traceback (most recent call last):
  File "/var/www/pynab/pynab/server.py", line 122, in scan
    status, overviews = self.connection.over((first, last))
  File "/var/www/pynab/lib/nntplib.py", line 966, in over
    fmt = self._getoverviewfmt()
  File "/var/www/pynab/lib/nntplib.py", line 650, in _getoverviewfmt
    resp, lines = self._longcmdstring("LIST OVERVIEW.FMT")
  File "/var/www/pynab/lib/nntplib.py", line 629, in _longcmdstring
    resp, list = self._getlongresp(file)
  File "/var/www/pynab/lib/nntplib.py", line 491, in _getlongresp
    resp = self._getresp()
  File "/var/www/pynab/lib/nntplib.py", line 473, in _getresp
    raise NNTPProtocolError(resp)
lib.nntplib.NNTPProtocolError: i\udcfdB\udcf0\udcc8\u065dj\udced\udcach\udce3\udcb1 \udc8a\udc9b\udcc2l\udcc6;\udccc\udcc6n\udc92\udcd4l\udcdf\udcf0\u04e4\udc9c\udcdf\udcefW\udcd69Q&\udce8\udc98\udcde$\udca6\udcd5r\udcc4udc8e`]\udca0.3(\udcccf\udcbc\udcc1l\udc9f\udcde2C\ud\udca7cTK\udc89\udccaa\udcf1\udc96!\udcf51\udcfb7(\udcd0f\udcbcm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/pynab/groups.py", line 84, in scan
    status, parts, messages, missed = server.scan(group_name, first=begin, last=end)
  File "/var/www/pynab/pynab/server.py", line 127, in scan
    self.connection.quit()
  File "/var/www/pynab/lib/nntplib.py", line 1069, in quit
    resp = self._shortcmd('QUIT')
  File "/var/www/pynab/lib/nntplib.py", line 615, in _shortcmd
    return self._getresp()
  File "/var/www/pynab/lib/nntplib.py", line 473, in _getresp
    raise NNTPProtocolError(resp)
\udc9aQ\udc8b\udcacq\udc98^V\udcbb\udcf1ai\udc8cw3\udca3\udc9b'\udcb8\udcaaX\udca8\u017eo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/lib/nntplib.py", line 1069, in quit
    resp = self._shortcmd('QUIT')
  File "/var/www/pynab/lib/nntplib.py", line 614, in _shortcmd
    self._putcmd(line)
  File "/var/www/pynab/lib/nntplib.py", line 443, in _putcmd
    self._putline(line)
  File "/var/www/pynab/lib/nntplib.py", line 435, in _putline
    self.file.write(line)
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/scan.py", line 39, in update
    return pynab.groups.scan(group_name, limit=config.scan.get('group_scan_limit', 2000000))
  File "/var/www/pynab/pynab/groups.py", line 123, in scan
    return True
  File "/var/www/pynab/pynab/server.py", line 34, in __exit__
    self.connection.quit()
  File "/var/www/pynab/lib/nntplib.py", line 1071, in quit
    self._close()
  File "/var/www/pynab/lib/nntplib.py", line 1193, in _close
    _NNTPBase._close(self)
  File "/var/www/pynab/lib/nntplib.py", line 1062, in _close
    self.file.close()
AttributeError: 'NNTP' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/pynab/scan.py", line 178, in <module>
    main(mode=mode, group=arguments['<group>'], date=arguments['--date'])
  File "/var/www/pynab/scan.py", line 116, in main
    data = r.result()
  File "/opt/local/lib/python3.3/concurrent/futures/_base.py", line 394, in result
    return self.__get_result()
  File "/opt/local/lib/python3.3/concurrent/futures/_base.py", line 353, in __get_result
    raise self._exception
  File "/opt/local/lib/python3.3/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/www/pynab/scan.py", line 44, in update
    traceback.format_exc(e)
  File "/opt/local/lib/python3.3/traceback.py", line 271, in format_exc
    format_exception(etype, value, tb, limit, chain))
  File "/opt/local/lib/python3.3/traceback.py", line 187, in format_exception
    list.extend(format_tb(tb, limit))
  File "/opt/local/lib/python3.3/traceback.py", line 75, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/opt/local/lib/python3.3/traceback.py", line 93, in extract_tb
    while tb is not None and (limit is None or n < limit):
TypeError: unorderable types: int() < AttributeError()
```

This is running on a Solaris based distro (OmniOS).
Let me know what other details I can provide, I'm not quite sure what data caused this to happen.

**Comment by gkoh** [comment]
My logs show this has occurred 82 times in the past 9 days, so there's a good chance it will happen again if any debug needs to be added then reproduced.

**Comment by brookesy2** [comment]
@Murodese Actually filed a bug with the library maintainers about this (I believe!). Let me see if I can dig it out.

**Comment by Murodese** [comment]
It's occurred since 0.0.1, it just stopped being reported until 1.5.1. No idea what the problem is - I filed a bug to Python a long time ago, but there's really no way to recreate it reliably so there's not much chance of a fix.

I believe the cause (after about a year of debugging) is with neither pynab nor python, but with the NNTP servers themselves. Some groups will report this exception constantly when you attempt to access them, and then they'll come good a few minutes or hours later. Changing server tends to make it go away temporarily (until it occurs again). My advice, generally, is to ignore it.

**Comment by gkoh** [comment]
Is there a way to catch the exception and keep going?
For my current installation, it takes out the scan process and then gets restarted by the daemon handlers.
(Looking at the backtraces the nested exceptions sure are ugly, if it's too difficult I can live with it).

**Comment by Murodese** [comment]
Most of the exceptions thrown from that are as a result of actually printing the NNTP error to the logs, since that brings its own shit with it (reading the line causes socket errors, printing the line causes unicode errors). Previous to 1.5.0?, it just didn't print the value of the NNTP error - the problem then being that you wouldn't see any normal errors, ie. "group doesn't exist" or the like. The exceptions thrown tend to be really random as well, so they can't be handled individually. I can change it back to how it was before (don't print the exception value), but it'll make standard debugging a bit more difficult.

**Comment by gkoh** [comment]
Thanks, I'm happy to leave it as is, since it's all still working for me.
I'd rather accept this than make debugging difficult, nothing is worse than being unable to trace issues that should be traceable.
