### ISSUE TITLE
Error when name is more than 512 characters

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#177]
Looks like it's choking when trying to inset a record into the database whose name is more than 512 characters.

It just loops through this process and doesn't seem to do anything else:

2015-03-06 23:35:26 INFO log: started pynab logger
2015-03-06 23:35:26 INFO postprocess: starting post-processing...
2015-03-06 23:35:26 INFO postprocess: starting with a quick post-process to clear out the cruft that's available locally...
2015-03-06 23:35:26 INFO postprocess: deleted 0 passworded releases
2015-03-06 23:35:26 CRITICAL Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 66, in process_requests
    return pynab.requests.process(500)
  File "/opt/pynab/pynab/requests.py", line 22, in process
    requests[int(release.name.split(': ')[1])] = release
ValueError: invalid literal for int() with base 10: 'b8878592fda380841dee2642c140ae1c'

2015-03-06 23:35:29 INFO rar: file info add [ae6d463809870e6a982de7395731b14c963dbc8e14eb5d2d8cb26de70ee97357]
2015-03-06 23:35:29 CRITICAL Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
psycopg2.DataError: value too long for type character varying(512)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 50, in process_rars
    return pynab.rars.process(100)
  File "/opt/pynab/pynab/rars.py", line 284, in process
    db.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (DataError) value too long for type character varying(512)
 'INSERT INTO files (name, size, release_id) VALUES (%(name)s, %(size)s, %(release_id)s) RETURNING files.id' {'release_id': 1512, 'size': 2016647403, 'name': "Û%|\x0eÀ*\x07º½°ó\x0e\x872ÇÛ\x8b\xa0\x1f8\x05ß\x01S!\x95NÍ+ÚóuPg>\x9bX.\x9f:p\x03!\x16r¿b;Æ\x16IqÌ\x9d\x83\x19 \x98è¥#\x15·fý\x975\x8e[ÅýìPÛÉ\x8d³Ï\x80U)\x10àGµ\xa0\x989NRÚÕ\x07\x13'ØY× E \x9dísDú¡\x9b¸P\x15ß$ÐìüÚ_Q!õï\x0b`Së\x1d\x96{±qéç\x8f¹Ó\x11\\\x84ßÙ\x8b:65\x8a\x0c\x9aç³\x87Jxö¯\x93®Å\x9aå®`ôÜ4\x90\x03Æ\x93[\x04Ç\x8a°^l\x9b\x1aBã\x02\x86®\x86cf\x04Ï\x8f\x0bºÈ1\x83\xa0\x11{\x88³ ¸fÔ<½ñ$¤y\x05!Ë^Oã;\x14°QÎYË>\x95\x9c\x04JI¾íY\x1aÛå\x03ªøÑ*½>÷\x03ê:ÃG¯\x0bÕîÓ©æyg\x97ðþ\x14\x8f)\x8eu|?·ßzÄ\x85¼f\x96DUù\tÀ\x07\x10 \x01\x9fóæL\x1dë\x99úÁH\x162\x05¦y2\x8d\x88ôF\x8fì\x1eâHWq:El\x83+\x85pªz]\x88\x9bÇ-kx/\x16Æ¿¿\r\x93'º\x89`Ø2:Å\x84a\x0f\x1c}Z\x90ôËF¶q\x86Z;3\x02\x13\x14\x14\x06ì\x07~(\x14Æ»\x1c\x93\x86[~§È\x81\x88ëÑð×¥ã;\x91\x9a\x80\tµ-.«Å1#Öfô\x96\x98ÄÙ¡ZA1£C´eq\x94µ\x15=ÑûÁn\x07è\x94/ÆÜ|o¹\x1dÄ\x95å\x99SÏ\x05aþ.\x05DÓ\x8c8ðLï\x9agÒu`î>^·\x81\x18L²±\x02Fµÿh\x8cÂe=I×Bf\x9atzÕB°í6ÚíÃè§Î\x92CtÝ¢\x0bþ\x90K,i\x92ö\x85Ã^\x07\x91£rÝ2büÚ\x82\x9a\x99Ä½¢ÂÎO\x9dìlÀX\x19+\x8a¹îX\x19HïPh/ü\x82\r\x16¶¹äf¤sí\x1cöMÛ\x8d\xadé\x14\x8c>ã5Ê>\n²\r\x9f\x80´\x19wÒQöp\x18Ã#ÿQ\x18úS\x9d»\x8aàÑ"}

**Comment by brookesy2** [comment]
I believe this is caused by a known issue with nntp where it spazzes out after a long time and spews out the above :(

**Comment by rembo10** [comment]
I think it happens with the same post though - I’ve reset it and everytime I re-add a.b.inner-sanctum, it throws this error……

any suggestions for a quick fix?

**Comment by brookesy2** [comment]
Very weird. You running master branch or dev?

**Comment by rembo10** [comment]
Master. I haven't really had a chance to dig into the code yet so I'm not really sure the best way to tackle something like this

**Comment by brookesy2** [comment]
@rembo10 https://github.com/Murodese/pynab/issues/174 This issue looks the same. Was a fix for dev branch. 

@Murodese Are these all spawning from the nntplib issue?

**Comment by rembo10** [comment]
I just deleted the release from the releases table and it seems to be chugging along again

**Comment by brookesy2** [comment]
Winner :) The fix was to truncate longer names.

**Comment by rembo10** [comment]
Oh nice, I'll switch to the develop branch. That's what I was thinking to do to solve this

**Comment by Murodese** [comment]
Yeah, that looks like NNTP garbage. Who's your news provider, out of interest?

**Comment by rembo10** [comment]
Supernews

**Comment by Murodese** [comment]
Yeeeeeeeeeeeeep. Not sure what the problem with their servers is, I queried them and hit level 1 support who promptly suggested that I should change servers to fix it, so presumably they're aware of it but not sure of the cause. I suspect it's just group corruption that clears up over time.

**Comment by rembo10** [comment]
Do you think it has something to do with this error also:
2015-03-07 04:12:22 INFO postprocess: starting post-processing...
2015-03-07 04:12:22 INFO postprocess: starting with a quick post-process to clear out the cruft that's available locally...
2015-03-07 04:12:22 INFO postprocess: deleted 0 passworded releases
2015-03-07 04:12:22 CRITICAL Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 66, in process_requests
    return pynab.requests.process(500)
  File "/opt/pynab/pynab/requests.py", line 22, in process
    requests[int(release.name.split(': ')[1])] = release
ValueError: invalid literal for int() with base 10: 'b8878592fda380841dee2642c140ae1c'

**Comment by rembo10** [comment]
Do you have a recommendation for a better provider?

**Comment by rembo10** [comment]
Maybe it's better to skip those articles rather than truncate the name?

**Comment by Murodese** [comment]
No recommendation for a better provider, all of them have the same problems - they just manifest slightly differently.

The articles are skipped already - or rather, they're retried later. For the garbage to end up where it is, though, it must've happened during a rar grab - which should already have appropriate safeguards. I assume it's pretty rare, though - I've never seen it happen before.

For the other: are you running master, or dev? Dev has no line 22 in requests. I've added a safeguard anyway.
