### ISSUE TITLE
Error When Renaming Bad Releases If Title Already Exists

### ISSUE THREAD

**Issue by rembo10** [Murodese/pynab#179]
Sorry to keep posting issues, but I really like this project. I'll start contributing once I have a chance to dig through the code. 

Ran into this error, when trying to rename a release with a name that already exists in the database:

Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 213, in <module>
    main()
  File "/opt/pynab/postprocess.py", line 125, in main
    scripts.rename_bad_releases.rename_bad_releases(8010)
  File "/opt/pynab/scripts/rename_bad_releases.py", line 22, in rename_bad_releases
    name, category_id = pynab.releases.discover_name(release)
  File "/opt/pynab/pynab/releases.py", line 66, in discover_name
    if release.files:
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/attributes.py", line 591, in get
    value = self.callable_(state, passive)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/strategies.py", line 534, in _load_for_state
    self.flush()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 518, in _emit_update_statements
    execute(statement, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "releases_name_posted_key"
DETAIL:  Key (name, posted)=(01 - Intro.flac, 2015-03-03 19:32:11) already exists.
 'UPDATE releases SET name=%(name)s, search_name=%(search_name)s, status=%(status)s, category_id=%(category_id)s WHERE releases.id = %(releases_id)s' {'releases_id': 43, 'name': '01 - Intro.flac', 'search_name': '01   Intro flac', 'status': 1, 'category_id': 3040}

I guess this can be solved with a try/except block, just not sure where to put it

**Comment by Murodese** [comment]
Haha, don't apologise for posting issues. When we're taking in such a massive amount of virtually random data, there's a pretty good chance that shit will break. Without feedback, there's no way we can catch the various errors that can come through.

I fixed this particular issue a while ago, and one of the fixes was to change the unique key (amongst some other stuff). That particular key, `release_name_posted_key` was deleted in an alembic migration a little while ago. If you're running the dev branch, did you run `./pynab.py update` to run the alembic migrations as well?

**Comment by rembo10** [comment]
I switched back to master because I was thinking about running this in a
production capacity. I'll test out the develop version as a fresh install
and just keep an eye out when updating

**Comment by Murodese** [comment]
No worries, I'll be re-merging dev/master and creating a new release pretty soon anyway.

Fixed in develop, 100c9650d4c5696531f19c1a8beb6ddced04522f.
