### ISSUE TITLE
sqlalchemy.exc.IntegrityError during postprocess, key already exists.

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#183]
I've run into a problem where the postprocess daemon is continually erroring and restarting with the following:
```
Traceback (most recent call last):
  File "/var/www/pynab/postprocess.py", line 213, in <module>
    main()
  File "/var/www/pynab/postprocess.py", line 125, in main
    scripts.rename_bad_releases.rename_bad_releases(8010)
  File "/var/www/pynab/scripts/rename_bad_releases.py", line 22, in rename_bad_releases
    name, category_id = pynab.releases.discover_name(release)
  File "/var/www/pynab/pynab/releases.py", line 66, in discover_name
    if release.files:
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/attributes.py", line 239, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/attributes.py", line 591, in get
    value = self.callable_(state, passive)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/strategies.py", line 534, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/strategies.py", line 603, in _emit_lazyload
    result = q.all()
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/query.py", line 2300, in all
    return list(self)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/query.py", line 2411, in __iter__
    self.session._autoflush()
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/session.py", line 1208, in _autoflush
    util.raise_from_cause(e)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/session.py", line 1198, in _autoflush
    self.flush()
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    mapper, table, update)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/persistence.py", line 518, in _emit_update_statements
    execute(statement, params)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/opt/local/lib/python3.3/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "releases_name_posted_key"
DETAIL:  Key (name, posted)=(resources\AdobePIM.dll, 2014-05-11 15:04:04) already exists.
 'UPDATE releases SET name=%(name)s, search_name=%(search_name)s, status=%(status)s, category_id=%(category_id)s WHERE releases.id = %(releases_id)s' {'category_id': 4010, 'status': 1, 'search_name': 'resources\\AdobePIM dll', 'name': 'resources\\AdobePIM.dll', 'releases_id': 56991}
```

My amateur check of the database shows that a release with that id and posted date does exist. However, I can't find anything with that name.
Let me know what other details I can dig out, this is causing my postprocess to restart every 4 minutes or so, I've had to stop it since its burning through my bandwidth.

**Comment by gkoh** [comment]
I deleted the releases with matching post dates to see if that avoids the exception (they were not interesting releases).

**Comment by gkoh** [comment]
Right before it dies, I see this in postprocess.log:
```
2015-03-11 08:26:30 INFO release: [Photoshop-Special Fuellmethoden Funktionsprinzip und kreative Ideen] - rename: resources\AdobePIM.dll (8010 -> 8010 -> 4010)
2015-03-11 08:26:31 INFO release: [Marius Schwiegk - Das E-Klasse T-Modell Die Jung-von-Matt-Kampagne] - rename: resources\AdobePIM.dll (8010 -> 8010 -> 4010)
2015-03-11 08:26:32 INFO release: [Pavel Kaplun - In meinem Aquarium Biomechanische Konstruktion] - rename: resources\AdobePIM.dll (8010 -> 8010 -> 4010)
```

**Comment by Murodese** [comment]
Is this on master or dev? That unique key no longer exists in Dev, and the bug was fixed previously.

**Comment by gkoh** [comment]
I'm running off the 1.5.1tag , which I think is the same as master right now.
If you can point me to the fix, I can try merging it into my sandbox, or do you recommend just switching to dev?

**Comment by Murodese** [comment]
Because it changes the db, I wouldn't recommend integrating it. Switch to dev temporarily (git checkout development-postgres, ./pynab.py update) and you can drop back to master when I merge the branches (probably later this week).

**Comment by gkoh** [comment]
OK, thanks, I've updated now and letting it run for a bit.
I'll close this once I can confirm the issue goes away.

Also, thanks for the blindingly quick replies!

**Comment by gkoh** [comment]
Well, it completed one postprocess iteration, where before it wasn't able to.
So, I declare this fixed for me.
Thanks once again.

**Comment by Murodese** [comment]
No problem, you managed to catch me just before I went to work :)
