### ISSUE TITLE
Multiple rows were found for one()

### ISSUE THREAD

**Issue by Enverex** [Murodese/pynab#196]
Just started running into this after restarting SupervisorD:

	2015-04-19 23:34:39,980 DEBG 'scan' stderr output:
	/usr/lib/python3.4/site-packages/sqlalchemy/sql/elements.py:3738: SAWarning: Textual SQL expression 'rownum % 100000=1' should be explicitly declared as text('rownum % 100000=1') (this warning may be suppressed after 10 occurrences)
	  {"expr": util.ellipses_string(element)})

	2015-04-19 23:34:39,982 DEBG 'scan' stderr output:
	Traceback (most recent call last):
	  File "/opt/pynab/scan.py", line 208, in <module>
		main(mode=mode, group=arguments['<group>'], date=arguments['--date'])
	  File "/opt/pynab/scan.py", line 116, in main
		process()
	  File "/opt/pynab/scan.py", line 78, in process
		pynab.releases.process()
	  File "/opt/pynab/pynab/releases.py", line 357, in process
		release.group = db.query(Group).filter(Group.name == binary.group_name).one()
	  File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2481, in one
		"Multiple rows were found for one()")
	sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()

	2015-04-19 23:34:40,057 DEBG fd 17 closed, stopped monitoring <POutputDispatcher at 140390395420400 for <Subprocess at 140390396195472 with name scan in state RUNNING> (stdout)>
	2015-04-19 23:34:40,057 DEBG fd 23 closed, stopped monitoring <POutputDispatcher at 140390395475584 for <Subprocess at 140390396195472 with name scan in state RUNNING> (stderr)>
	2015-04-19 23:34:40,058 INFO exited: scan (exit status 1; not expected)

**Comment by Enverex** [comment]
Actually it looks like I may have accidentally added a duplicate group so that's the cause.
