### ISSUE TITLE
Post-processing error

### ISSUE THREAD

**Issue by boo1234** [Murodese/pynab#204]
So after a few weeks of no movies being snatched by CouchPotato, I decided to look into what was going on. Checking my supervisor stderr logs for the `postproc` script, I see the following. Further, I see that supervisor is constantly trying to start postproc after it dies, which is to be expected.

```
2015-06-17 22:17:41 INFO  log: started pynab logger
2015-06-17 22:17:41 INFO  postprocess: starting post-processing...
2015-06-17 22:17:41 INFO  postprocess: starting with a quick post-process to clear out the cruft that's available locally...
Traceback (most recent call last):
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: update or delete on table "metablack" violates foreign key constraint "releases_movie_metablack_id_fkey" on table "releases"
DETAIL:  Key (id)=(190062) is still referenced from table "releases".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/boo1234/software/pynab/postprocess.py", line 223, in <module>
    main()
  File "/home/boo1234/software/pynab/postprocess.py", line 79, in main
    scripts.quick_postprocess.local_postprocess()
  File "/home/boo1234/software/pynab/scripts/quick_postprocess.py", line 13, in local_postprocess
    db.query(MetaBlack).filter(MetaBlack.status=='IMPOSSIBLE').filter((MetaBlack.movie!=None)|(MetaBlack.tvshow!=None)).delete(synchronize_session=False)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2818, in delete
    delete_op.exec_()
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1074, in exec_
    self._do_exec()
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 1252, in _do_exec
    mapper=self.mapper)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1023, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1339, in _handle_dbapi_exception
    exc_info
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/boo1234/.virtualenvs/pynab/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "metablack" violates foreign key constraint "releases_movie_metablack_id_fkey" on table "releases"
DETAIL:  Key (id)=(190062) is still referenced from table "releases".
 [SQL: 'DELETE FROM metablack WHERE metablack.status = %(status_1)s AND ((EXISTS (SELECT 1 \nFROM releases \nWHERE metablack.id = releases.movie_metablack_id)) OR (EXISTS (SELECT 1 \nFROM releases \nWHERE metablack.id = releases.tvshow_metablack_id)))'] [parameters: {'status_1': 'IMPOSSIBLE'}]
```

**Comment by brookesy2** [comment]
Have you run 'alembic upgrade head' lately?

Looks like its trying to remove from metblack but its referenced elsewhere.

**Comment by Murodese** [comment]
Yeah, I know what's causing this. I'll fix it when I get home.

**Comment by brookesy2** [comment]
The hero we need :)

**Comment by boo1234** [comment]
@Murodese, I'll happily try to pitch in if you can share where the bug is... and submit a bug report. Just having my server spinning that proc up and down is keeping its fan going. :)

**Comment by Murodese** [comment]
Normally I'd do so, but it's an SQLAlchemy thing and needs a db migration, so it's easier for me to do it :)

**Comment by Murodese** [comment]
Try that: `./pynab.py update`

**Comment by jaddison** [comment]
`postproc` isn't dying anymore - and there's some serious database action goin' on. Nice work @Murodese! I'll see what happens over the course of the next few hours, if movie results start showing up.

Thanks!

**Comment by boo1234** [comment]
looks good, i think this can be closed
