### ISSUE TITLE
getnfo API call causes Internal Server Error

### ISSUE THREAD

**Issue by gkoh** [Murodese/pynab#214]
If I try to retrieve an nfo with the 't=getnfo' API call, the pynab API issues an exception.

eg.
```
https://pynaburl/api?t=getnfo&guid=nnnn&apikey=xxxx
```
results in this wsgi error:
```
 Traceback (most recent call last):
   File "/opt/local/lib/python3.3/site-packages/bottle.py", line 862, in _handle
     return route.call(**args)
   File "/opt/local/lib/python3.3/site-packages/bottle.py", line 1729, in wrapper
     rv = callback(*a, **ka)
   File "/var/www/pynab/api.py", line 56, in api
     data = func(dataset)
   File "./pynab/api.py", line 54, in get_nfo
     release = db.query(Release).join(NFO).filter(Release.id == id).one()
   File "/opt/local/lib/python3.3/site-packages/sqlalchemy/orm/query.py", line 2375, in one
     raise orm_exc.NoResultFound("No row was found for one()")
 sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by gkoh** [comment]
This appears working for me now, closing.
