### ISSUE TITLE
Size processing rarely finds releases that are multiple exabytes in size.

### ISSUE THREAD

**Issue by Murodese** [Murodese/pynab#233]
```
Traceback (most recent call last):
  File "/opt/pynab/postprocess.py", line 57, in process_rars
    return pynab.rars.process(100)
  File "/opt/pynab/pynab/rars.py", line 287, in process
    db.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2015, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2133, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 2097, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 694, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.DataError) bigint out of range
 [SQL: 'UPDATE releases SET size=%(size)s, passworded=%(passworded)s WHERE releases.id = %(releases_id)s'] [parameters: {'releases_id': 1395899, 'passworded': 'NO', 'size': 13895540990126658663}]
```

@gkoh: I think this is coming from the rar header processing? It has a sensible size for the initial calcuation during release building.

```
Name: Uiniynuqon-3828023592-201512071158
Group: a.b.multimedia
Posted: 2015-12-07 01:21:44
Initial Size: 6163219360
Size from RAR check: 13895540990126658663
```

**Comment by gkoh** [comment]
> @gkoh: I think this is coming from the rar header processing? It has
> a sensible size for the initial calcuation during release building.
> Name: Uiniynuqon-3828023592-201512071158
> Group: a.b.multimedia
> Posted: 2015-12-07 01:21:44
> Initial Size: 6163219360
> Size from RAR check: 13895540990126658663

Quite possibly.
I'll try to pull the rar headers this weekend and check them against
the rar library.

**Comment by gkoh** [comment]
Found it.
The rar library we use doesn't understand encrypted block headers, which are different to passworded releases. So it blindly decodes encrypted fields and essentially returns garbage.
It always had this problem, however, since we fixed the 64-bit length support it's more obvious when it happens.

I'll post a fix in the next day or so, ensuring these releases are marked as passworded.

**Comment by Murodese** [comment]
Fantastic, thanks for taking a look at that.

**Comment by gkoh** [comment]
See how that goes.
Not extensively tested, but a fairly surgical fix, so I don't expect adverse results.

**Comment by Murodese** [comment]
Looks like it worked fine on my install.
