### ISSUE TITLE
Error when removing groups

### ISSUE THREAD

**Issue by paulouderkirk** [Murodese/pynab#258]
It seems that removing a group that has releases causes the following error:

```
pdo@ubuntu:/var/www/pynab$ python3 pynab.py group disable alt.binaries.backup
group disabled.

pdo@ubuntu:/var/www/pynab$ python3 pynab.py group remove alt.binaries.backup
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: update or delete on table "groups" violates foreign key constraint "releases_group_id_fkey" on table "releases"
DETAIL:  Key (id)=(945) is still referenced from table "releases".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pynab.py", line 263, in <module>
    remove_group(arguments['<group>'])
  File "pynab.py", line 137, in remove_group
    if pynab.groupctl.remove_group(group):
  File "/var/www/pynab/pynab/groupctl.py", line 24, in remove_group
    deleted = db.query(Group).filter(Group.name == group_name).delete()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 3048, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 1127, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 1311, in _do_exec
    mapper=self.mapper)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 1046, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "groups" violates foreign key constraint "releases_group_id_fkey" on table "releases"
DETAIL:  Key (id)=(945) is still referenced from table "releases".
 [SQL: 'DELETE FROM groups WHERE groups.name = %(name_1)s'] [parameters: {'name_1': 'alt.binaries.backup'}]
```

Am I doing something obviously wrong here?  

Thanks!

**Comment by jamesmeneghello** [comment]
Generally speaking, you shouldn't be removing groups, just deactivating 
them. What are you trying to do?

Paul D. Ouderkirk wrote:

**Comment by paulouderkirk** [comment]
I suppose mostly I was trying to grok the difference between "disable" and "remove" :)

**Comment by paulouderkirk** [comment]
Oh right, here's what I was trying to do: delete a group (alt.binaries.backup) so pynab would stop trying to to form binaries/releases from the millions and millions of segments I have in the database.

**Comment by jamesmeneghello** [comment]
For something like that, it's probably easiest to just use a query:

`DELETE FROM binaries WHERE group_id = ?` where ? is the ID of a.b.backup.
