### ISSUE TITLE
Unable to Initialize Database

### ISSUE THREAD

**Issue by britai** [Murodese/pynab#260]
Hi

 New install, postgresql 9.5, freebsd 9.3 jail, python 3.4.
 The database initialization is failing out with

pynab@pynab:~/pynab % python3 install.py
## Welcome to Pynab.

Please ensure that you have copied and renamed config_sample.py to config.py before proceeding.
You need to put in your details, too. If you are migrating from Newznab, check out scripts/convert_from_newznab.py first.

This script is destructive. Ensure that the database credentials and settings are correct.
The supplied database really should be empty, but it'll just drop anything it wants to overwrite.

To continue, press enter. To exit, press ctrl-c.
pandas is required to use nzedb pre import: pip install pandas
Building tables...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Installing admin user...
Copying groups into db...
Copying categories into db...
Copying TV data into db...
Problem inserting data into database: 'ascii' codec can't encode characters in position 3-10: ordinal not in range(128)

 When I comment out that portion of install.py, it starts out of the movie part and tells me 

pynab@pynab:~/pynab % python3 install.py
## Welcome to Pynab.

Please ensure that you have copied and renamed config_sample.py t
You need to put in your details, too. If you are migrating from N

This script is destructive. Ensure that the database credentials
The supplied database really should be empty, but it'll just drop

To continue, press enter. To exit, press ctrl-c.
pandas is required to use nzedb pre import: pip install pandas
Building tables...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Installing admin user...
Copying groups into db...
Copying categories into db...
Copying movie data into db...
Updating regex...
Traceback (most recent call last):
  File "install.py", line 103, in <module>
    pynab.util.update_regex()
  File "/usr/local/pynab/pynab/util.py", line 117, in update_rege                                                                     x
    db.merge(r)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/ses                                                                     sion.py", line 1712, in merge
    self._autoflush()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/ses                                                                     sion.py", line 1305, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/ses                                                                     sion.py", line 2027, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/ses                                                                     sion.py", line 2145, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/la                                                                     nghelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/co                                                                     mpat.py", line 183, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/ses                                                                     sion.py", line 2109, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/uni                                                                     tofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/uni                                                                     tofwork.py", line 532, in execute
    uow
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/per                                                                     sistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/orm/per                                                                     sistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/sql/ele                                                                     ments.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, p                                                                     arams)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/util/co                                                                     mpat.py", line 183, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python3.4/site-packages/sqlalchemy/engine/                                                                     default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode characters in posi                                                                     tion 93-99: ordinal not in range(128)

I'm a little stumped here. The pynab install is a clone of a couple days ago.

 Thank you!

**Comment by jamesmeneghello** [comment]
Is postgres configured to use utf-8?

**Comment by britai** [comment]
That was it. I reconfigured the inittb to use UTF8 per http://www.postgresql.org/docs/9.0/static/multibyte.html

Thank you!!!

**Comment by jamesmeneghello** [comment]
No problem :)
