### ISSUE TITLE
Converting from Newznab

### ISSUE THREAD

**Issue by pdupreez** [Murodese/pynab#265]
I get an error which I cannot quite work out where the issue is:

pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

I use:

python3 scripts/convert_from_newznab.py --mysql-user root --mysql-passwd admin --mysql-port 3306 localhost newznab

**Comment by brookesy2** [comment]
I don't use mysql a ton, but I am gonna take a long shot guess. Does 127.0.0.1 work instead of localhost?

**Comment by pdupreez** [comment]
I tried both the local IP, 127.0.0.1. Neither worked

**Comment by brookesy2** [comment]
Are you able to connect to mysql using its normal command line tools?

**Comment by pdupreez** [comment]
Yes, I have no problem connecting via console.

`pdupreez@htpc:/opt/pynab$ mysql -u root -padmin
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 154
Server version: 5.5.47-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.

mysql>`

The one area which I am not clear about is the config.py settings for the
PostgresDB, and if that impacts here?

My settings are as follow:

`# main db server config

# mostly self-explanatory

db = {
    # engine: which db server type to use
    # 'postgresql' or 'mysql+pymysql'
    # maria, percona, etc use the latter
    'engine': 'postgresql',
    'host': '192.168.1.234',
    'port': 5432,
    'unix_socket': '',
    'user': 'root',
    'pass': 'admin',
    'db': 'pynab',
}`

The port here is different, but I assume that would be the case.

My /etc/mysql/my.cnf settings are:

`# This will be passed to all mysql clients

# It has been reported that passwords should be enclosed with ticks/quotes

# especially if they contain "#" chars...

# Remember to edit /etc/mysql/debian.cnf when changing the socket location.

[client]
port            = 3306
socket          = /var/run/mysqld/mysqld.sock`

I don't know if there is somewhere else where I should look?

**Comment by pdupreez** [comment]
I changed the port to 3306 in config.py and used the server's IP address 192.168.1.234 as follow:

pdupreez@htpc:/opt/pynab$ python3 scripts/convert_from_newznab.py --mysql-user root --mysql-passwd admin --mysql-port 3306 192.168.1.234 newznab

It seems to connect now, but I get a new error now:

Converting users...
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 1044, in _do_get
    return self._pool.get(wait, self._timeout)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/queue.py", line 145, in get
    raise Empty
sqlalchemy.util.queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.**connect()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(_cargs, *_cparams)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(_cargs, *_cparams)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/__init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: received invalid response to SSL negotiation: [

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/convert_from_newznab.py", line 204, in <module>
    convert_users(mysql)
  File "scripts/convert_from_newznab.py", line 92, in convert_users
    db.query(User).delete()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/query.py", line 3048, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 1127, in exec_
    self._do_exec()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/persistence.py", line 1311, in _do_exec
    mapper=self.mapper)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 1046, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 910, in _connection_for_bind
    engine, execution_options)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 334, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 1060, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 1057, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.**connect()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(_cargs, *_cparams)
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(_cargs, *_cparams)
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/__init**.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) received invalid response to SSL negotiation: [

**Comment by jamesmeneghello** [comment]
To be clear: are you trying to convert from newznab on mysql to pynab on mysql, or pynab on postgres?

**Comment by pdupreez** [comment]
HI James

I am trying to go from newznab (mySQL) to pynab (postgres)

**Comment by jamesmeneghello** [comment]
Only thing I can think of here is that Postgres isn't running on that port, or something's intercepting it and doing something weird. Firewall? Using weird SSL certs?
