### ISSUE TITLE
sqlalchemy.exc.ProgrammingError: (ProgrammingError) can't adapt type 'ObjectId'

### ISSUE THREAD

**Issue by xsivart** [Murodese/pynab#66]
Hi there!

Went to start doing a convert from mongodb to postgresql and I received the following error:

Please ensure that you have copied and renamed config.sample.py to config.py before proceeding.

This script is destructive. Ensure that the database credentials and settings are correct.
The supplied database really should be empty, but it'll just drop anything it wants to overwrite.

To continue, press enter. To exit, press ctrl-c.
INFO  [alembic.migration] Context impl PostgresqlImpl.
INFO  [alembic.migration] Will assume transactional DDL.
Copying blacklists...
Copying regexes...
Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 917, in _execute_context
    context)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/default.py", line 432, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'ObjectId'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/convert_mongo_to_postgre.py", line 61, in <module>
    postgre.commit()
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 765, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 370, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 1903, in flush
    self._flush(objects)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 2021, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/util/compat.py", line 168, in reraise
    raise value
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/session.py", line 1985, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
    rec.execute(self)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/unitofwork.py", line 523, in execute
    uow
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    mapper, table, insert)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/orm/persistence.py", line 562, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 720, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/sql/elements.py", line 317, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 817, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 1108, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/util/compat.py", line 174, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/util/compat.py", line 167, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/base.py", line 917, in _execute_context
    context)
  File "/usr/lib64/python3.3/site-packages/sqlalchemy/engine/default.py", line 432, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) can't adapt type 'ObjectId' 'INSERT INTO regexes (id, regex, description, status, ordinal, group_name) VALUES (%(id)s, %(regex)s, %(description)s, %(status)s, %(ordinal)s, %(group_name)s)' ({'regex': '/^(?P<name>[a-z0-9]{12,})\s?\[(?P<parts>\d{1,3}\/\d{1,3})/i', 'status': True, 'id': ObjectId('529644b86a39e87e8e098db6'), 'ordinal': 10, 'group_name': '._', 'description': 'catchall hashes'}, {'regex': '/^._?usenet4ever._?"(?P<name>._?)( WW|)( REPOST|)\.(pdb|htm|prc|lit|epub|lrf|txt|pdf|rtf|doc|chf|chn|mobi|chm|doc|sample|mkv|Avi|mp4|vol|ogm|par|rar|sfv|nfo|nzb|srt|ass|mpg|txt|zip|wmv|ssa|r\d{1,3}|7z|tar|mov|divx|m2ts|rmvb|iso|dmg|sub|idx|rm|ac3|t\d{1,2}|u\d{1,3})._?\ \-\ darkness\ yenc$/iS', 'status': False, 'id': ObjectId('529644b86a39e87e8e098db7'), 'ordinal': 1, 'group_name': '._', 'description': ''}, {'regex': '/^\"(?P<name>._?)\.(lit|pdb|htm|prc|lit|epub|lrf|txt|pdf|rtf|doc|chf|chn|mobi|chm|doc|sample|mkv|Avi|mp4|vol|ogm|par|rar|sfv|nfo|nzb|srt|ass|mpg|txt|zip|wmv|ssa|r\d{1,3}|7z|tar|mov|divx|m2ts|rmvb|iso|dmg|sub|idx|rm|ac3|t\d{1,2}|u\d{1,3})._?\[(?P<parts>\d{1,3}( of |\/)\d{1,3})._?elitenzb\.net/iS', 'status': False, 'id': ObjectId('529644b86a39e87e8e098db8'), 'ordinal': 1, 'group_name': '._', 'description': ''}, {'regex': '/^nzbgrabit\.com.(?P<name>\w._?)\((?P<parts>\d{1,4}\/\d{1,4})/i', 'status': False, 'id': ObjectId('529644b86a39e87e8e098db9'), 'ordinal': 1, 'group_name': '._', 'description': ''}, {'regex': '/^PWP\ +?\"(?P<name>._?)\.(par|vol|rar|sfv|nfo|nzb)._?\ \[(?P<parts>\d{1,3}\/\d{1,3})\]\ \-\ yenc$/i', 'status': False, 'id': ObjectId('529644b86a39e87e8e098dba'), 'ordinal': 1, 'group_name': '.*', 'description': ''}, {'regex': '/^\"P2H\-(?P<name>[a-zA-Z0-9\ \-\\'\&\(\)\_]+?)\.._?\"\ yEnc$/', 'status': False, 'id': ObjectId('529644b86a39e87e8e098dbb'), 'ordinal': 1, 'group_name': '._', 'description': 'no its not as crazy as you think'}, {'regex': '/^\"B4E\-(?P<name>._?)\.(sample|mkv|Avi|mp4|vol|ogm|par|rar|sfv|nfo|nzb|srt|ass|mpg|txt|zip|wmv|ssa|r\d{1,3}|7z|tar|mov|divx|m2ts|rmvb|iso|dmg|sub|idx|rm|ac3|t\d{1,2}|u\d{1,3})/S', 'status': False, 'id': ObjectId('529644b86a39e87e8e098dbc'), 'ordinal': 1, 'group_name': '._', 'description': 'hoping these have a valid name once filelist is built...'}, {'regex': '/^\[(?P<name>._?)\] \\- \((?P<parts>\d{1,3}\/\d{1,3})\)/i', 'status': False, 'id': ObjectId('529644b86a39e87e8e098dbd'), 'ordinal': 9, 'group_name': '._', 'description': ''}  ... displaying 10 of 1746 total bound parameter sets ...  {'regex': '/(?P<name>[a-z0-9\.\_\ \(\)]{20,}\-[a-z0-9]+)/i', 'status': True, 'id': 5004.0, 'ordinal': 9.0, 'group_name': 'alt.binaries.movies', 'description': ''}, {'regex': '/(?P<name>[a-z0-9\.\_\ \(\)]{20,}\-[a-z0-9]+)/i', 'status': True, 'id': 5005.0, 'ordinal': 9.0, 'group_name': 'alt.binaries.music', 'description': ''})

**Comment by MathengeNewton** [comment]
i have a similar issue with sqlalchemy and postgress none of these suggestions seem to be working for me
